### ISSUE TITLE
How to use plugin along with Symfony's PHPUnit bridge?

### ISSUE THREAD

**Issue by Wirone** [psalm/psalm-plugin-phpunit#89] opened 2020-09-28 11:13 UTC
Since [Symfony PHPUnit bridge](https://symfony.com/doc/current/components/phpunit_bridge.html) installs PHPUnit in separate directory (not with other vendors) after installing Psalm's PHPUnit plugin I have 2 different versions of PHPUnit installed in the project (and my tests fail, which is different story..).

I would like Psalm to use already installed PHPUnit, with just proper configuration / bootstrap files.

How to achieve that?

**Comment by VincentLanglet** [comment] 2020-12-01 11:10
The phpstan phpunit plugin does not require phpunit.
https://github.com/phpstan/phpstan-phpunit/blob/master/composer.json

I personally use it without phpunit by adding the following config.
```
    bootstrapFiles:
        - symfony/bin/.phpunit/phpunit-9.3-0/vendor/autoload.php
```

IMHO @weirdan @muglug, the `Phpunit` dependency should be removed from this plugin because we can provide it from somewhere else. When using the Symfony phpunit bridge, something like this could work: 
```
    <extraFiles>
        <directory name="symfony/bin/.phpunit/phpunit-9.3-0"/>
    </extraFiles>
```

**Comment by enumag** [comment] 2020-12-07 08:52
Possibly relevant: https://github.com/symfony/symfony/issues/36202

**Comment by VincentLanglet** [comment] 2020-12-07 09:11
> Possibly relevant: [symfony/symfony#36202](https://github.com/symfony/symfony/issues/36202)

I just read this and it seem that
- Requiring `phpunit/phpunit` is not recommended
- https://github.com/symfony/symfony/issues/36202#issuecomment-643751206 is the recommended approach in PHPStan (so I think that `extraFiles` should be the recommended way too with psalm)

**Comment by desmax** [comment] 2020-12-09 10:32
with new version 0.14 tried to add
```    
   <extraFiles>
        <directory name="bin/.phpunit/phpunit"/>
    </extraFiles>
```
but no luck

**Comment by VincentLanglet** [comment] 2020-12-09 11:57
> with new version 0.14 tried to add
> 
> ```
>    <extraFiles>
>         <directory name="bin/.phpunit/phpunit"/>
>     </extraFiles>
> ```
> 
> but no luck

Hi, it worked fine for me.

Which command are you running ? Which version of psalm do you use ? @desmax

**Comment by desmax** [comment] 2020-12-09 12:11
@VincentLanglet 
```
➜ vendor/bin/psalm -v
Psalm 4.3.1@2feba22a005a18bf31d4c7b9bdb9252c73897476
```

my full config is
```
<?xml version="1.0"?>
<psalm
    errorLevel="1"
    resolveFromConfigFile="true"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
>
    <projectFiles>
        <directory name="src"/>
        <directory name="tests"/>
        <ignoreFiles>
            <directory name="vendor"/>
        </ignoreFiles>
    </projectFiles>
    <extraFiles>
        <directory name="bin/.phpunit/phpunit"/>
    </extraFiles>
    <plugins>
        <pluginClass class="Weirdan\DoctrinePsalmPlugin\Plugin"/>
        <pluginClass class="Psalm\PhpUnitPlugin\Plugin"/>
        <pluginClass class="Psalm\SymfonyPsalmPlugin\Plugin"/>
    </plugins>
</psalm>
```

and I still get this
```
➜ vendor/bin/psalm
Scanning files...
Uncaught OutOfBoundsException: Package "phpunit/phpunit" is not installed in /Users/max/code/sh/vendor/composer/InstalledVersions.php:1940
Stack trace:
#0 /Users/max/code/sh/vendor/composer/package-versions-deprecated/src/PackageVersions/Versions.php(255): Composer\InstalledVersions::getPrettyVersion('phpunit/phpunit')
#1 /Users/max/code/sh/vendor/psalm/plugin-phpunit/src/VersionUtils.php(20): PackageVersions\Versions::getVersion('phpunit/phpunit')
#2 /Users/max/code/sh/vendor/psalm/plugin-phpunit/src/Plugin.php(15): Psalm\PhpUnitPlugin\VersionUtils::packageVersionIs('phpunit/phpunit', '<', '8.0')
#3 /Users/max/code/sh/vendor/vimeo/psalm/src/Psalm/Config.php(1245): Psalm\PhpUnitPlugin\Plugin->__invoke(Object(Psalm\PluginRegistrationSocket), NULL)
#4 /Users/max/code/sh/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(584): Psalm\Config->initializePlugins(Object(Psalm\Internal\Analyzer\ProjectAnalyzer))
#5 /Users/max/code/sh/vendor/vimeo/psalm/src/psalm.php(676): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/Users/max/code...', true)
#6 /Users/max/code/sh/vendor/vimeo/psalm/psalm(2): require_once('/Users/max/code...')
#7 {main}

Next Psalm\Exception\ConfigException: Failed to load plugin Psalm\PhpUnitPlugin\Plugin in /Users/max/code/sh/vendor/vimeo/psalm/src/Psalm/Config.php:1247
Stack trace:
#0 /Users/max/code/sh/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(584): Psalm\Config->initializePlugins(Object(Psalm\Internal\Analyzer\ProjectAnalyzer))
#1 /Users/max/code/sh/vendor/vimeo/psalm/src/psalm.php(676): Psalm\Internal\Analyzer\ProjectAnalyzer->check('/Users/max/code...', true)
#2 /Users/max/code/sh/vendor/vimeo/psalm/psalm(2): require_once('/Users/max/code...')
#3 {main}
(Psalm 4.3.1@2feba22a005a18bf31d4c7b9bdb9252c73897476 crashed due to an uncaught Throwable)
```

**Comment by desmax** [comment] 2020-12-09 12:27
@VincentLanglet what if you run `vendor/bin/psalm --clear-cache`, will it still work for you?

the problem is  here Psalm\PhpUnitPlugin\Plugin
```
        if (VersionUtils::packageVersionIs('phpunit/phpunit', '<', '8.0')) {
            $psalm->addStubFile(__DIR__ . '/../stubs/Assert_75.phpstub');
        }
```
I don't  see how this will work, since it checks only versions installed via composer

**Comment by VincentLanglet** [comment] 2020-12-09 13:53
@desmax Whoah, I made a stupid mistake, the plugin was removed from my config

What does work:
- Thanks to the extraFiles section, I have no `missingDependencies` reported.

What does not work:
- Loading this plugin

I got the same error than you, but I think it's possible to fix it ; in 
https://github.com/psalm/psalm-plugin-phpunit/blob/master/src/VersionUtils.php
We should change
```
$currentVersion = (string) explode('@', Versions::getVersion($package))[0];
```
into
```
try {
    $currentVersion = (string) explode('@', Versions::getVersion($package))[0];
} catch (\OutOfBoundsException $exception) {
    return false;
}
```

But then I get
```
Uncaught ReflectionException: Class PHPUnit\Framework\TestCase does not exist in /var/www/vagrant.assurancevie.com/current/symfony/vendor/symfony/framework-bundle/Test/ForwardCompatTestTrait.php:18
Stack trace:
#0 /var/www/vagrant.assurancevie.com/current/symfony/vendor/symfony/framework-bundle/Test/ForwardCompatTestTrait.php(18): ReflectionMethod->__construct('PHPUnit\\Framewo...', 'tearDown')
#1 /var/www/vagrant.assurancevie.com/current/symfony/vendor/composer/ClassLoader.php(444): include('/var/www/vagran...')
#2 /var/www/vagrant.assurancevie.com/current/symfony/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/vagran...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Bundle\\...')
#4 [internal function]: spl_autoload_call('Symfony\\Bundle\\...')
#5 /var/www/vagrant.assurancevie.com/current/symfony/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/TraitFinder.php(64): trait_exists('Symfony\\Bundle\\...')
#6 /var/www/vagrant.assurancevie.com/current/symfony/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/ClassLikes.php(642): Psalm\Internal\PhpVisitor\TraitFinder->getNode()
#7 /var/www/vagrant.assurancevie.com/current/symfony/vendor/psalm/plugin-phpunit/src/Hooks/TestCaseHandler.php(137): Psalm\Internal\Codebase\ClassLikes->getTraitNode('Symfony\\Bundle\\...')
#8 /var/www/vagrant.assurancevie.com/current/symfony/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ClassAnalyzer.php(962): Psalm\PhpUnitPlugin\Hooks\TestCaseHandler::afterStatementAnalysis(Object(PhpParser\Node\Stmt\Class_), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Internal\Analyzer\ClassAnalyzer), Object(Psalm\Codebase), Array)
#9 /var/www/vagrant.assurancevie.com/current/symfony/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FileAnalyzer.php(211): Psalm\Internal\Analyzer\ClassAnalyzer->analyze(Object(Psalm\Context), Object(Psalm\Context))
#10 /var/www/vagrant.assurancevie.com/current/symfony/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(340): Psalm\Internal\Analyzer\FileAnalyzer->analyze(NULL)
#11 /var/www/vagrant.assurancevie.com/current/symfony/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(579): Psalm\Internal\Codebase\Analyzer->Psalm\Internal\Codebase\{closure}(0, '/var/www/vagran...')
#12 /var/www/vagrant.assurancevie.com/current/symfony/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php(269): Psalm\Internal\Codebase\Analyzer->doAnalysis(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1)
#13 /var/www/vagrant.assurancevie.com/current/symfony/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(1184): Psalm\Internal\Codebase\Analyzer->analyzeFiles(Object(Psalm\Internal\Analyzer\ProjectAnalyzer), 1, false, false)
#14 /var/www/vagrant.assurancevie.com/current/symfony/vendor/vimeo/psalm/src/psalm.php(678): Psalm\Internal\Analyzer\ProjectAnalyzer->checkPaths(Array)
#15 /var/www/vagrant.assurancevie.com/current/symfony/vendor/vimeo/psalm/psalm(2): require_once('/var/www/vagran...')
#16 {main}
```

I tried changing to
```
    <extraFiles>
        <file name="symfony/bin/.phpunit/phpunit/vendor/autoload.php"/>
    </extraFiles>
```
without success.

I would need some help (cc @muglug) to understand the difference between `extraFiles` and the `boostrapFiles` option of phpstan (cc @ondrejmirtes). We may improve something on psalm files loading.

**Comment by ondrejmirtes** [comment] 2020-12-09 14:00
Psalm's `extraFiles` are PHPStan's `scanFiles` https://phpstan.org/user-guide/discovering-symbols#third-party-code-outside-of-composer-dependencies, Psalm has no `bootstrap` option AFAIK.

**Comment by VincentLanglet** [comment] 2020-12-09 14:10
Oh ! Thanks, by looking for a `boostrap` option I found
https://github.com/vimeo/psalm/issues/2037

So the right way is to use 
```
autoloader="symfony/bin/.phpunit/phpunit/vendor/autoload.php"
```

**Comment by VincentLanglet** [comment] 2020-12-09 14:16
@desmax Can you confirm that this work with 
https://github.com/psalm/psalm-plugin-phpunit/pull/103

and by using 
```
autoloader="symfony/bin/.phpunit/phpunit/vendor/autoload.php"
```
instead of extraFiles ?

**Comment by desmax** [comment] 2020-12-09 14:35
@VincentLanglet it does work, it  also works fine without autoloader config, only with #103 changes

**Comment by muglug** [comment] 2020-12-10 00:47
Ok, closing — thanks all!

**Closed by muglug** 2020-12-10 00:47 UTC
